/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LLIST_H_RPCGEN
#define _LLIST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum color {
	ORANGE = 0,
	PUCE = 1,
	TURQUOISE = 2,
};
typedef enum color color;

struct list {
	char *data;
	int key;
	color col;
	struct list *next;
};
typedef struct list list;

#define PRINTER 0x2fffffff
#define PRINTER_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINT_LIST 1
extern  int * print_list_1(list *, CLIENT *);
extern  int * print_list_1_svc(list *, struct svc_req *);
#define SUM_LIST 2
extern  int * sum_list_1(list *, CLIENT *);
extern  int * sum_list_1_svc(list *, struct svc_req *);
extern int printer_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINT_LIST 1
extern  int * print_list_1();
extern  int * print_list_1_svc();
#define SUM_LIST 2
extern  int * sum_list_1();
extern  int * sum_list_1_svc();
extern int printer_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_color (XDR *, color*);
extern  bool_t xdr_list (XDR *, list*);

#else /* K&R C */
extern bool_t xdr_color ();
extern bool_t xdr_list ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LLIST_H_RPCGEN */
